Repository acenturyandabit/fortknight, pull requests merged in 2022-10, with the labels that each got.

#78 Add new game mode: „Tornado Mode“
  index.html
  js/dom_events.js
  js/main.js
  js/piece_object.js
Labels: enhancement

#65 Added more information to the readme
  images/debug.jpg
  images/fortknight.jpg
  readme.md
Labels: documentation, good first issue, up for grabs

#80 Simplify the DarkMode-Function
  css/styles.css
  index.html
  js/achievements_highscores.js
  js/dark_mode.js
Labels: code-quality

#81 Simplified board-generation
  css/styles.css
  index.html
  js/main.js
Labels: code-quality
